apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: global-tenant-resourcs
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/samirtahir91/acm-test
    revision: "HEAD"
    branch: "capsule-self-serve"
    dir: "./globalTenantResources/envs/dev/dev-cluster"
    auth: none