apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: namespaces
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/samirtahir91/acm-test
    revision: "HEAD"
    branch: "capsule"
    dir: "./envs/dev/dev-cluster"
    auth: none