resources:
- ../../../../../../base

patches:

# Patch Tenant spec
- path: patch.yaml
  target:
    kind: Tenant

# Patch tenant name
- target:
    kind: Tenant
  patch: |-
    - op: replace
      path: /metadata/name
      value: tenant-abc123