resources:
- ../../../../../../base

patches:

# Patch global labels and annotations
- path: patch.yaml
  target:
    kind: Tenant

# Patch tenant
- target:
    kind: Tenant
  patch: |-
    - op: replace
      path: /metadata/name
      value: tenant-abc123

    # Owner group
    - op: replace
      path: /spec/owners/0/name
      value: tenant-abc123-maintainers@mydomain.dev

    # Owner group cluster role
    - op: add
      path: /spec/owners/0/clusterRoles/-
      value: dev-cluster-maintainers

    # Rolebindings
    - op: add
      path: /spec/additionalRoleBindings/-
      value:
        clusterRoleName: dev-cluster-developers
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: tenant-abc123-developers@mydomain.dev
    - op: add
      path: /spec/additionalRoleBindings/-
      value:
        clusterRoleName: dev-cluster-maintainers
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: tenant-abc123-maintainers@mydomain.dev
    - op: add
      path: /spec/additionalRoleBindings/-
      value:
        clusterRoleName: dev-cluster-pim
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: tenant-abc123-pim@mydomain.dev

    # ResourceQuota
    # This is moved to global tenant resources - label tenant "quota=xxxx"
    # - To map predefined quotas to tenants
    # If custom fine graned values, better to patch like this:
    #- op: add
    #  path: /spec/resourceQuotas
    #  value:
    #    scope: Namespace
    #    items: 
    #      - hard:
    #          pods: "5"
    #          requests.cpu: "1"
    #          limits.cpu: "1"
    #          requests.memory: "1Gi"
    #          limits.memory: "1Gi"     
