apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: acm-test
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/samirtahir91/acm-test
    revision: "HEAD"
    branch: "main"
    dir: "."
    auth: token
    secretRef:
      name: github-pat
