apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: csi-driver
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  sourceType: git
  git:
    auth: none
    dir: ./csi-kusto
    branch: main
    repo: https://github.com/samirtahir91/acm-test
