apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: csi-driver
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  sourceType: oci
  oci:
    image: europe-west2-docker.pkg.dev/playpen-746314/csi-kusto/csi-driver:v1
    dir: .
    auth: gcpserviceaccount
    gcpServiceAccountEmail: gar-reader@playpen-746314.iam.gserviceaccount.com
