resources:
- ../../../../../../base

patches:

- target:
    kind: Tenant
  patch: |-
    - op: replace
      path: /metadata/name
      value: tenant-abc123

    # Rolebindings
    - op: add
      path: /spec/additionalRoleBindings/-
      value:
        clusterRoleName: dev-cluster-developers
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: tenant-abc123-developers
    - op: add
      path: /spec/additionalRoleBindings/-
      value:
        clusterRoleName: dev-cluster-maintainers
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: tenant-abc123-maintainers
    - op: add
      path: /spec/additionalRoleBindings/-
      value:
        clusterRoleName: dev-cluster-pim
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: tenant-abc123-pim

    # ResourceQuota
    - op: add
      path: /spec/resourceQuotas
      value:
        scope: Namespace
        items: 
          - hard:
              pods: "5"
              requests.cpu: "1"
              limits.cpu: "1"
              requests.memory: "1Gi"
              limits.memory: "1Gi"     

- target:
    kind: GlobalTenantResource
  patch: |-
    - op: replace
      path: /metadata/name
      value: tenant-resources-abc123
    # ServiceAccount
    - op: replace
      path: /spec/resources/0/namespacedItems/0/namespace
      value: ns-abc123

- target:
    kind: TenantResource
  patch: |-
    - op: replace
      path: /metadata/name
      value: tenant-resources-abc123
    - op: replace
      path: /metadata/namespace
      value: ns-abc123
    # ServiceAccount
    - op: replace
      path: /spec/resources/0/rawItems/0/metadata/name
      value: ksa-abc123

- target:
    kind: Namespace
  patch: |-
    - op: replace
      path: /metadata/name
      value: ns-abc123
    - op: replace
      path: /metadata/annotations/config.kubernetes.io~1depends-on
      value: capsule.clastix.io/Tenant/tenant-abc123
    - op: replace
      path: /metadata/labels/capsule.clastix.io~1tenant
      value: tenant-abc123