apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: replace-me
spec:
  owners:
  - name: system:serviceaccount:config-management-system:root-reconciler-namespaces
    kind: ServiceAccount
  resourceQuotas:
    scope: Namespace
    items:
    - hard:
        pods: "10"
  networkPolicies:
    items:
    - policyTypes:
      - Ingress
      - Egress
      podSelector: {}