apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: replace-me
  labels:
    tenant: caas
spec:
  namespaceOptions:
    #quota: 100 # Optionally limit no. of namespaces allowed for the Tenant
    forbiddenLabels:
      denied:
          - foo.acme.net
      deniedRegex: .*.acme.net
