apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: replace-me
  labels:
    tenant: caas
spec:
  owners:
  - name: alice
    kind: User
  namespaceOptions:
    forbiddenLabels:
      denied:
          - foo.acme.net
      deniedRegex: .*.acme.net
  additionalRoleBindings: []
  # these are moved to a glolbal tenant resource
  #networkPolicies:
  #  items:
  #  - policyTypes:
  #    - Ingress
  #    - Egress
  #    podSelector: {}
