apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: replace-me
  labels:
    tenant: caas
spec:
  owners:
  - name: system:serviceaccount:config-management-system:root-reconciler-namespaces
    kind: ServiceAccount
  namespaceOptions:
    forbiddenLabels:
      denied:
          - foo.acme.net
      deniedRegex: .*.acme.net
  additionalRoleBindings: []
  # these could be moved to a glolbal tenant resource
  networkPolicies:
    items:
    - policyTypes:
      - Ingress
      - Egress
      podSelector: {}
