apiVersion: capsule.clastix.io/v1beta2
kind: TenantResource
metadata:
  name: replace-me
  namespace: replace-me
spec:
  resyncPeriod: 60s
  resources:
    - rawItems:
        - apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: replace-me