apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: replace-me
  labels:
    tenant: caas
spec:
  owners:
  - name: replace-me # can create namesapces (should be tenant maintainer group)
    kind: Group
    # If clusterRoles not specd, owners get cluster-admin on the tenant namespaces by default
    clusterRoles: []
      # refined clusterrole patched in subteam kustomization.yaml
  namespaceOptions:
    forbiddenLabels:
      denied:
          - foo.acme.net
      deniedRegex: .*.acme.net
  additionalRoleBindings: []
  # these are moved to a glolbal tenant resource
  #networkPolicies:
  #  items:
  #  - policyTypes:
  #    - Ingress
  #    - Egress
  #    podSelector: {}
