# This can be synced in a seperate rootsync, i.e. with the capsule system itself
---
apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource 
metadata:
  name: gts-caas-rsq-default-blue
  labels:
    colour: blue
spec:
  tenantSelector:
    matchLabels:
      quota: default
  resyncPeriod: 60s
  resources:
    - rawItems:
        - apiVersion: v1
          kind: ResourceQuota
          metadata:
            name: rsq-caas-default
          spec:
            hard:
              pods: "1"
              requests.cpu: "1"
              limits.cpu: "1"
              requests.memory: "1Gi"
              limits.memory: "1Gi"     
---
apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource 
metadata:
  name: gts-caas-rsq-low-blue
  labels:
    colour: blue
spec:
  tenantSelector:
    matchLabels:
      quota: low
  resyncPeriod: 60s
  resources:
    - rawItems:
        - apiVersion: v1
          kind: ResourceQuota
          metadata:
            name: rsq-caas-low
          spec:
            hard:
              pods: "10"
              requests.cpu: "2"
              limits.cpu: "2"
              requests.memory: "2Gi"
              limits.memory: "2Gi"     